// client/src/layouts/WorkspaceLayout.svelte
<script lang="ts">
  import type {
    Snippet,
  } from "svelte";

  import AgentsSidebar from "../components/AgentsSidebar/index.svelte";
    import { mockAgents } from "../data/mockAgent";

  let {
    children,
  }: {
    children: Snippet;
  } = $props();
</script>

<div class="workspace">
  <header class="workspace__titlebar">
    <div class="workspace__title">
      <span class="workspace__app-icon">▣</span>
      <span>AGENT WORKSPACE</span>
    </div>

    <div class="workspace__controls">
      <button type="button" aria-label="Minimize">—</button>
      <button type="button" aria-label="Maximize">□</button>
      <button type="button" aria-label="Close">×</button>
    </div>
  </header>

  <nav class="workspace__menu">
    <button type="button">File</button>
    <button type="button">View</button>
    <button type="button">Tools</button>
    <button type="button">Window</button>
    <button type="button">Help</button>
  </nav>

  <div class="workspace__body">
    <AgentsSidebar agents={mockAgents} />

    <main class="workspace__content">
      {@render children()}
    </main>
  </div>

  <footer class="workspace__statusbar">
    <div class="workspace__status">
      <span class="workspace__status-light"></span>
      READY
    </div>

    <div>WORKSPACE: DEFAULT</div>

    <div class="workspace__status-spacer"></div>

    <div>{mockAgents.length} AGENTS</div>
    <div>BUILD 1.0.0</div>
  </footer>
</div>

// client/src/layouts/WorkspaceLayout/index.tsx
import {
  useEffect,
} from "react";

import {
  reatomComponent,
} from "@reatom/react";

import {
  Outlet,
} from "react-router";

import {
  AgentsSidebar,
} from "../../components/AgentsSidebar";

import styles from "./styles.module.scss";
import { agents } from "../../model/agents";
import { metadata } from "../../model/metadata";

export const WorkspaceLayout = reatomComponent(() => {
  const identities = agents.list.data();

  const isReady =
    agents.list.ready() &&
    metadata.load.ready()

  const error =
    agents.list.error() ??
    metadata.load.error();

  useEffect(() => {
    const controller = new AbortController();

    void agents.list(controller.signal);

    void metadata.load(controller.signal);

    return () => controller.abort();
  }, []);

  const status =
    error
      ? "ERROR"
      : isReady
        ? "READY"
        : "LOADING";

  const agentsLabel =
    identities.length === 1
      ? "AGENT"
      : "AGENTS";

  return (
    <div
      className={
        styles.workspace
      }
    >
      <header
        className={
          styles.titlebar
        }
      >
        <div
          className={
            styles.title
          }
        >
          <span
            className={
              styles.appIcon
            }
            aria-hidden="true"
          >
            ▣
          </span>

          <span>
            AGENT WORKSPACE
          </span>
        </div>

        <div
          className={
            styles.windowControls
          }
        >
          <button
            type="button"
            aria-label="Minimize"
          >
            —
          </button>

          <button
            type="button"
            aria-label="Maximize"
          >
            □
          </button>

          <button
            type="button"
            aria-label="Close"
          >
            ×
          </button>
        </div>
      </header>

      <nav
        className={styles.menu}
        aria-label="Application menu"
      >
        <button type="button">
          File
        </button>

        <button type="button">
          View
        </button>

        <button type="button">
          Tools
        </button>

        <button type="button">
          Window
        </button>

        <button type="button">
          Help
        </button>
      </nav>

      <div
        className={styles.body}
      >
        <AgentsSidebar />

        <main
          className={
            styles.content
          }
        >
          <Outlet />
        </main>
      </div>

      <footer
        className={
          styles.statusbar
        }
      >
        <div
          className={
            styles.status
          }
        >
          <span
            className={
              styles.statusLight
            }
            aria-hidden="true"
          />

          {status}
        </div>

        <div>
          WORKSPACE: DEFAULT
        </div>

        <div
          className={
            styles.statusSpacer
          }
        />

        <div>
          {identities.length}{" "}
          {agentsLabel}
        </div>

        <div>
          BUILD 1.0.0
        </div>
      </footer>
    </div>
  );
});
