// client/src/components/Chat/index.tsx
import {
  reatomComponent,
} from "@reatom/react";
import type { AgentModel } from "../../model/agent/model";
import { Message } from "./Message";
import styles from "./styles.module.scss";
import {
  useState,
} from "react";
import type { ChatModel } from "../../model/chat/model";

type ChatProps = {
  agent: AgentModel;
  chat: ChatModel;
};

export const Chat =
  reatomComponent(({
    agent,
    chat
  }: ChatProps) => {
    const [
      query,
      setQuery,
    ] = useState("");

    const messages =
      chat.messages();

    const runStatus =
      chat.run.status();

    const sendReady =
      chat.run.start.ready();

    const sendError =
      chat.run.start.error();

    const stopReady =
      chat.run.stop.ready();
    const isRunning = runStatus === "running";

    const canSend =
      !isRunning &&
      sendReady &&
      query.trim().length > 0 &&
      agent.configForm().model.length > 0;

    const canStop =
      isRunning &&
      stopReady;

    const handleSend =
      async (): Promise<void> => {
        const nextQuery =
          query.trim();

        if (
          !nextQuery ||
          !canSend
        ) {
          return;
        }

        const {
          name: _name,
          ...body
        } =
          agent.configForm();

        setQuery("");

        try {
          await chat.run.start({
            body,
            query: nextQuery,
          });
        } catch {
          // chat.run.start.error()
        }
      };

    const handleStop =
      async (): Promise<void> => {
        if (!canStop) {
          return;
        }

        try {
          await chat.run.stop();
        } catch {
          // chat.run.stop.error()
        }
      };

    return (
      <section
        className={styles.panel}
      >
        <div
          className={styles.body}
        >
          <section
            className={
              styles.messages
            }
          >
            {messages.map(
              (message, index) => (
                <Message
                  key={index}
                  role={message.role}
                  status={message.status}
                  content={message.content}
                />
              ),
            )}

            {sendError && (
              <div
                className={
                  styles.error
                }
                role="alert"
              >
                {sendError.message}
              </div>
            )}
          </section>

          <footer
            className={
              styles.bottomBar
            }
          >
            <textarea
              className={
                styles.input
              }
              value={query}
              placeholder={
                isRunning
                  ? "Agent is running..."
                  : "Введите сообщение..."
              }
              onChange={(
                event,
              ) => {
                setQuery(
                  event
                    .currentTarget
                    .value,
                );
              }}
              onKeyDown={(
                event,
              ) => {
                if (
                  event.key ===
                  "Enter" &&
                  !event.shiftKey
                ) {
                  event.preventDefault();

                  void handleSend();
                }
              }}
            />

            <button
              className={
                isRunning
                  ? styles.stop
                  : styles.send
              }
              type="button"
              disabled={
                isRunning
                  ? !canStop
                  : !canSend
              }
              onClick={() => {
                if (isRunning) {
                  void handleStop();
                } else {
                  void handleSend();
                }
              }}
            >
              {isRunning
                ? stopReady
                  ? "STOP"
                  : "STOPPING..."
                : sendReady
                  ? "SEND"
                  : "SENDING..."}
            </button>
          </footer>
        </div>
      </section>
    );
  });

// client/src/components/Chat/index.svelte
<script lang="ts">
    import { agentState, infoState } from "../../store/index.svelte";
    import Message from "../Message/index.svelte";
    import "./styles.css";
    import {
        callAgent,
        clearHistory,
        stopAgent,
    } from "../../api/callAgent";

    let query = $state("");

    const lastMessage = $derived(agentState.messages.at(-1));

    async function send(e: Event) {
        e.preventDefault();

        if (
            lastMessage?.role === "assistant" &&
            lastMessage.status === "in_progress"
        ) {
            await stopAgent(agentState.runId!);
            return;
        }

        const text = query.trim();
        if (!text) return;

        query = "";

        await callAgent({
            query: text,
            files: [...agentState.files],
        });
    }
</script>

<div class="interface">
    <header class="header">
        <div class="titlebar">
            <h1 class="title">Chat</h1>
            <div class="title-controls">
                <button class="button">c</button>
                <button class="button">ev</button>
                <button class="button clear" onclick={clearHistory}>✕</button>
            </div>
        </div>
        <nav class="menubar">
            <span>File</span>
            <span>Edit</span>
            <span>View</span>
            <span>Help</span>
        </nav>
    </header>

    <div class="window-body">
        <section class="messages">
            {#each agentState.messages as m}
                <Message content={m.content} role={m.role} status={m.status} />
            {/each}
        </section>

        <footer class="bottom-bar">
            <!-- <input
                bind:this={fileInput}
                class="file-input"
                type="file"
                multiple
                accept=".txt,.md,.json,.csv,.xml,.js,.ts"
                onchange={(e) => {
                    const input = e.currentTarget as HTMLInputElement;
                    files = Array.from(input.files ?? []);
                }}
            />

            <button
                class="file-button"
                type="button"
                onclick={() => fileInput?.click()}
                disabled={uploading ||
                    lastMessage?.status === "in_progress" ||
                    !!infoState.error ||
                    infoState.loading}
            >
                [ FILE ]
            </button>

            <div class="file-label" title={files.map((f) => f.name).join(", ")}>
                {filesLabel}
            </div> -->

            <textarea
                class="input main"
                bind:value={query}
                placeholder="Введите сообщение..."
                onkeydown={async (e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                        send(e);
                    }
                }}
            ></textarea>

            <button
                class="send"
                onclick={async (e) => await send(e)}
                disabled={!!infoState.error || infoState.loading}
            >
                {lastMessage?.status === "in_progress"
                    ? "[ STOP ]"
                    : "[ SEND ]"}
            </button>
        </footer>
    </div>
</div>
